### ISSUE TITLE
ImportError: No module named management.commands.testmigrate

### ISSUE THREAD

**Issue by peterlauri** [greyside/django-testmigrate#2]
Tried this out, but didn't get anywhere with the version from pypi. Steps (and output below):
- created new virtual env
- installed django and django-testmigrate
- started new project and new app
- added django_testmigrate to INSTALLED_APPS
- run ./manage.py testmigrate

```
➜  plauri@Peters-MacBook-Pro test-django-testmigrate  virtualenv .ve
New python executable in .ve/bin/python2.7
Also creating executable in .ve/bin/python
Installing setuptools, pip...done.
➜  plauri@Peters-MacBook-Pro test-django-testmigrate  source .ve/bin/activate
(.ve)➜  plauri@Peters-MacBook-Pro test-django-testmigrate  pip install django django-testmigrate
Downloading/unpacking django
  Downloading Django-1.7.2-py2.py3-none-any.whl (7.4MB): 7.4MB downloaded
Downloading/unpacking django-testmigrate
  Downloading django_testmigrate-0.2.0-py2-none-any.whl
Downloading/unpacking six (from django-testmigrate)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: django, django-testmigrate, six
Successfully installed django django-testmigrate six
Cleaning up...
(.ve)➜  plauri@Peters-MacBook-Pro test-django-testmigrate  django-admin.py startproject testmigrateproject
(.ve)➜  plauri@Peters-MacBook-Pro test-django-testmigrate  ls -lart
total 0
drwxr-xr-x  3 plauri  staff  102 Jan 12 11:16 ..
drwxr-xr-x  6 plauri  staff  204 Jan 12 11:17 .ve
drwxr-xr-x  4 plauri  staff  136 Jan 12 11:18 testmigrateproject
drwxr-xr-x  4 plauri  staff  136 Jan 12 11:18 .
(.ve)➜  plauri@Peters-MacBook-Pro test-django-testmigrate  cd testmigrateproject
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  ls -lrt
total 8
drwxr-xr-x  6 plauri  staff  204 Jan 12 11:18 testmigrateproject
-rwxr-xr-x  1 plauri  staff  261 Jan 12 11:18 manage.py
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  ./manage.py startapp app1
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  nano testmigrateproject/settings.py
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  ./manage.py testmigrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.testmigrate
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  ./manage.py shell
Python 2.7.9 (default, Dec 19 2014, 06:00:59)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> settings.INSTALLED_APPS
('django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django_testmigrate')
>>>
```

**Comment by peterlauri** [comment]
This is not reproducible when installing directly from source.

```
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  pip install --upgrade -e ~/work/opensource/django-testmigrate
Obtaining file:///Users/plauri/work/opensource/django-testmigrate
  Running setup.py (path:/Users/plauri/work/opensource/django-testmigrate/setup.py) egg_info for package from file:///Users/plauri/work/opensource/django-testmigrate

Requirement already up-to-date: django>=1.7 in /Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages (from django-testmigrate==0.2.0)
Requirement already up-to-date: six in /Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages (from django-testmigrate==0.2.0)
Installing collected packages: django-testmigrate
  Running setup.py develop for django-testmigrate

    Creating /Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django-testmigrate.egg-link (link to .)
    Adding django-testmigrate 0.2.0 to easy-install.pth file

    Installed /Users/plauri/work/opensource/django-testmigrate
Successfully installed django-testmigrate
Cleaning up...
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  ./manage.py testmigrate
Creating test database for alias 'default'...
Operations to perform:
  Apply all migrations: admin, contenttypes, auth, app1, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying app1.0001_initial... OK
  Applying sessions.0001_initial... OK
Destroying test database for alias 'default'...
Operations to perform:
  Target specific migration: 0001_initial, from admin
Running migrations:
  No migrations to apply.
Operations to perform:
  Target specific migration: 0001_initial, from app1
Running migrations:
  No migrations to apply.
Operations to perform:
  Target specific migration: 0001_initial, from auth
Running migrations:
  No migrations to apply.
Operations to perform:
  Target specific migration: 0001_initial, from contenttypes
Running migrations:
  No migrations to apply.
Operations to perform:
  Target specific migration: 0001_initial, from sessions
Running migrations:
  No migrations to apply.
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject
```

**Comment by peterlauri** [comment]
This is reproducible from last commit in master.

```
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  pip install --upgrade https://github.com/greyside/django-testmigrate/archive/ddd8da843fc6c9bc0a559d0362e34e45ae370a65.zip
Downloading/unpacking https://github.com/greyside/django-testmigrate/archive/ddd8da843fc6c9bc0a559d0362e34e45ae370a65.zip
  Downloading ddd8da843fc6c9bc0a559d0362e34e45ae370a65.zip (unknown size): 24kB downloaded
  Running setup.py (path:/var/folders/c0/mqpfg67n03jd64wb5qr1_mdm0000gn/T/pip-6eR155-build/setup.py) egg_info for package from https://github.com/greyside/django-testmigrate/archive/ddd8da843fc6c9bc0a559d0362e34e45ae370a65.zip

Requirement already up-to-date: django>=1.7 in /Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages (from django-testmigrate==0.2.0)
Requirement already up-to-date: six in /Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages (from django-testmigrate==0.2.0)
Installing collected packages: django-testmigrate
  Found existing installation: django-testmigrate 0.2.0
    Uninstalling django-testmigrate:
      Successfully uninstalled django-testmigrate
  Running setup.py install for django-testmigrate

Successfully installed django-testmigrate
Cleaning up...
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject  ./manage.py testmigrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/plauri/work/play/test-django-testmigrate/.ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management.commands.testmigrate
(.ve)➜  plauri@Peters-MacBook-Pro testmigrateproject
```
